### PR TITLE
Jakarta migration

### PR DESCRIPTION
**Pull request by rrajoria**
We will be merging it to master once ACS 23.1 is released

### CODE REVIEW

**Review by SaraAspery — CHANGES_REQUESTED** [review]
LGTM, it just needs the year updating in the license headers of the changed classes. We had to do the same for alfresco-community-repo, and used this in gnu sed to do it in one go: `git diff master --name-only | grep -E ".java$" | xargs gsed -i -E 's/(\*\sCopyright\s\(C\)\s2005\s-\s)[0-9]{4}(\sAlfresco Software Limited)/\12023\2/'`

**Review by kmagdziarz — CHANGES_REQUESTED** [review]
LGTM but headers should be updated.

**Comment by rrajoria** [comment]
Thanks for Reviewing .

I will be updating the license header in a separate PR so that it is easy to track the spring 6 changes

**Review by MohinishSah — APPROVED** [review]

**Review by kmagdziarz — APPROVED** [review]

**Comment by rrajoria** [comment]
> LGTM, it just needs the year updating in the license headers of the changed classes. We had to do the same for alfresco-community-repo, and used this in gnu sed to do it in one go: `git diff master --name-only | grep -E ".java$" | xargs gsed -i -E 's/(\*\sCopyright\s\(C\)\s2005\s-\s)[0-9]{4}(\sAlfresco Software Limited)/\12023\2/'`

Thanks for Reviewing .

I will be updating the license header in a separate PR so that it is easy to track the spring 6 changes

**Review by pzhyland — APPROVED** [review]

**Pull request merged**
